version: '3.1'

services:
   app:
     image: neo4j:3.3
     ports:
       - "7687:7687"
       - "7474:7474"
     volumes:
       - neo4j_data:/data
     deploy:
       labels:
         - "APP=neo4j"
       replicas: 1
       restart_policy:
         condition: any

volumes:
    neo4j_data:
